[tool:pytest]
minversion = 8.0
testpaths = tests
addopts =
	--strict-markers
	--strict-config
	--cov=benchmark
	--cov-report=term-missing
	--cov-fail-under=90

[coverage:run]
branch = True
source = benchmark

[coverage:report]
show_missing = True
skip_covered = True

[metadata]
license_files = LICENSE
